import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          richColors
          position="top-right"
          toastOptions={{
            classNames: {
              success: "bg-green-500 text-white border border-green-600",
              error: "bg-red-500 text-white border border-red-600",
              info: "bg-blue-500 text-white border border-blue-600",
              warning: "bg-yellow-500 text-black border border-yellow-600",
              default: "bg-gray-800 text-white border border-gray-600",
            },
          }}
        />
      </body>
    </html>
  );
}
